# Generated by Django 3.0.4 on 2026-04-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_json', models.TextField(help_text='구글 인증 토큰 JSON 데이터')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
