# Generated by Django 3.0.4 on 2026-04-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleoauthtoken',
            name='id',
        ),
        migrations.AddField(
            model_name='googleoauthtoken',
            name='email',
            field=models.EmailField(default='john8707@gmail.com', help_text='구글 계정 이메일', max_length=254, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
