# Generated by Django 3.0.4 on 2020-03-27 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('starttime', models.CharField(max_length=255)),
                ('endtime', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255, null=True)),
                ('div', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('not_available', models.IntegerField()),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='AccountingDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('value', models.IntegerField()),
                ('note', models.TextField()),
                ('remark', models.TextField(null=True)),
                ('accounting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AccountingTitle')),
            ],
        ),
    ]
