# Generated by Django 3.0.4 on 2020-03-25 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('location', models.CharField(max_length=255, null=True)),
                ('div', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('not_available', models.IntegerField()),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Schedule')),
            ],
        ),
    ]
