# Generated by Django 3.0.4 on 2020-03-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='endtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='starttime',
            field=models.TimeField(),
        ),
    ]
