# Generated by Django 3.0.4 on 2020-03-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200321_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountingdetails',
            old_name='title',
            new_name='accounting_id',
        ),
    ]
