# Generated by Django 3.0.4 on 2020-03-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200327_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
