# Generated by Django 3.0.4 on 2020-05-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeUser',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gisu', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('location', models.CharField(max_length=255, null=True)),
                ('div', models.IntegerField()),
                ('is_current', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('songname', models.CharField(max_length=255)),
                ('bass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bass', to='practice.PracticeUser')),
                ('drum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drum', to='practice.PracticeUser')),
                ('guitar1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guitar1', to='practice.PracticeUser')),
                ('guitar2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guitar2', to='practice.PracticeUser')),
                ('keyboard1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyboard1', to='practice.PracticeUser')),
                ('keyboard2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyboard2', to='practice.PracticeUser')),
                ('vocal1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocal1', to='practice.PracticeUser')),
                ('vocal2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocal2', to='practice.PracticeUser')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('not_available', models.IntegerField()),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.Schedule')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.PracticeUser')),
            ],
        ),
    ]
