# Generated by Django 3.0.4 on 2023-10-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyNotComing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whynotcoming', to='practice.Schedule')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.PracticeUser')),
            ],
        ),
    ]
