# Generated by Django 3.0.4 on 2025-04-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
    ]
