# Generated by Django 3.0.4 on 2025-04-26 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20250426_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='user_name',
        ),
        migrations.AddField(
            model_name='session',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='session', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
