# Generated by Django 3.0.4 on 2023-02-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20200519_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='rooms',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
