# Generated by Django 3.0.4 on 2025-04-28 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_auto_20250426_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrivaltime',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='kakaotalkid',
            name='user_name',
        ),
        migrations.AddField(
            model_name='arrivaltime',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='arrivaltime', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kakaotalkid',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='kakaotalkid', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
