# Generated by Django 3.0.4 on 2023-02-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_schedule_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceuser',
            name='gisu',
        ),
        migrations.RemoveField(
            model_name='practiceuser',
            name='phonenumber',
        ),
    ]
