# Generated by Django 3.0.4 on 2023-02-09 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_auto_20230209_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=255)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.SongData')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.PracticeUser')),
            ],
        ),
    ]
