# Generated by Django 3.0.4 on 2024-03-04 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_auto_20231106_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('arrival_time', models.TimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivaltime', to='practice.PracticeUser')),
            ],
        ),
    ]
