# Generated by Django 3.0.4 on 2024-03-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_arrivaltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivaltime',
            name='confirmed_arrival_time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
