# Generated by Django 3.0.4 on 2024-03-12 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_arrivaltime_confirmed_arrival_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_name', models.CharField(blank=True, max_length=255)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='practice.Schedule')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='practice.SongData')),
            ],
        ),
    ]
