# Generated by Django 3.0.4 on 2023-02-22 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_auto_20230209_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='practice.SongData'),
        ),
    ]
