# Generated by Django 3.0.4 on 2023-03-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_auto_20230222_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='div',
            new_name='min_per_song',
        ),
    ]
