# Generated by Django 3.0.4 on 2024-03-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='room_name',
        ),
        migrations.AddField(
            model_name='timetable',
            name='room_number',
            field=models.IntegerField(default=0),
        ),
    ]
