# Generated by Django 3.0.4 on 2024-03-15 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_auto_20240312_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='KakaoTalkId',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kakaotalkid', to='practice.PracticeUser')),
            ],
        ),
    ]
