# Generated by Django 3.0.4 on 2024-04-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0011_arrivaltime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceCheck',
        ),
    ]
