# Generated by Django 3.0.4 on 2024-07-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0012_delete_attendancecheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='room_number',
        ),
        migrations.AddField(
            model_name='timetable',
            name='room_name',
            field=models.CharField(default='room', max_length=255),
        ),
    ]
