# Generated by Django 3.0.4 on 2024-12-06 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0013_auto_20240729_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songdata',
            name='priority',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
