# Generated by Django 3.0.4 on 2024-12-06 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0014_auto_20241206_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songdata',
            name='priority',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
